{% set name = "sphinxext-opengraph" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinxext-opengraph-{{ version }}.tar.gz
  sha256: cc48d6e572190f25b730f391732566697181fad1c4573e33fc6f45d23a2f074e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
  run:
    # Not in setup.py, but referenced in code (automatically installed by Sphinx)
    - docutils
    - python >=3.7
    - matplotlib-base
    - sphinx >=4.0

test:
  imports:
    - sphinxext.opengraph
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wpilibsuite/sphinxext-opengraph
  summary: Sphinx Extension to enable OGP support
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - manics
