{% set name = "sphinxext-opengraph" %}
{% set version = "0.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinxext-opengraph-{{ version }}.tar.gz
  sha256: b7db74764f5bc28a32f03ed6bf97a131a5f29dc9aeff8745282a83f6096602e4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
  run:
    # Not in setup.py, but referenced in code (automatically installed by Sphinx)
    - docutils
    - python >=3.7
    - sphinx >=4.0

test:
  imports:
    - sphinxext.opengraph
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wpilibsuite/sphinxext-opengraph
  summary: Sphinx Extension to enable OGP support
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - manics
